import type { CoreIdentityData } from "../schemas/index.js";
import type { DesignSynthesisFile } from "./design-synthesis.js";
import { isTokenWorthy } from "./confidence.js";

/**
 * Compile core-identity.yaml into DTCG tokens.json format.
 * Only includes values with medium+ confidence.
 */
export function compileDTCG(
  identity: CoreIdentityData,
  clientName: string,
  synthesis?: DesignSynthesisFile | null,
): Record<string, unknown> {
  const brand: Record<string, unknown> = {
    color: compileColors(identity.colors),
    typography: compileTypography(identity.typography),
  };

  const tokens: Record<string, unknown> = {
    $name: `${clientName} Design Tokens`,
    $description: `Generated by brandsystem.app — schema 0.1.0`,
    brand,
  };

  if (identity.spacing) {
    brand.spacing = compileSpacing(identity.spacing);
  } else if (synthesis) {
    const spacing = compileSynthesisSpacing(synthesis);
    if (Object.keys(spacing).length > 0) brand.spacing = spacing;
  }

  if (synthesis) {
    const radius = compileSignalGroup(synthesis.shape.radius_scale, "dimension");
    if (Object.keys(radius).length > 0) brand.radius = radius;

    const shadow = compileSignalGroup(synthesis.depth.shadow_scale, "shadow");
    if (Object.keys(shadow).length > 0) brand.shadow = shadow;

    const layout = compileLayout(synthesis);
    if (Object.keys(layout).length > 0) brand.layout = layout;

    const motion = compileMotion(synthesis);
    if (Object.keys(motion).length > 0) brand.motion = motion;
  }

  return tokens;
}

function compileColors(
  colors: CoreIdentityData["colors"]
): Record<string, unknown> {
  const group: Record<string, unknown> = {};

  for (const color of colors) {
    if (!isTokenWorthy(color.confidence)) continue;

    const key = color.role === "unknown" ? slugify(color.name) : color.role;
    group[key] = {
      $value: color.value,
      $type: "color",
      $description: color.name,
      $extensions: {
        "com.brandsystem": {
          source: color.source,
          confidence: color.confidence,
          ...(color.figma_variable_id && { figmaVariableId: color.figma_variable_id }),
        },
      },
    };
  }

  return group;
}

function compileTypography(
  typography: CoreIdentityData["typography"]
): Record<string, unknown> {
  const group: Record<string, unknown> = {};

  for (const entry of typography) {
    if (!isTokenWorthy(entry.confidence)) continue;

    const key = slugify(entry.name);
    const typeGroup: Record<string, unknown> = {
      family: {
        $value: entry.family,
        $type: "fontFamily",
      },
    };

    if (entry.size) {
      typeGroup.size = { $value: entry.size, $type: "dimension" };
    }
    if (entry.weight) {
      typeGroup.weight = { $value: entry.weight, $type: "fontWeight" };
    }
    if (entry.line_height) {
      typeGroup.lineHeight = { $value: entry.line_height, $type: "dimension" };
    }

    group[key] = typeGroup;
  }

  return group;
}

function compileSpacing(
  spacing: NonNullable<CoreIdentityData["spacing"]>
): Record<string, unknown> {
  if (!isTokenWorthy(spacing.confidence)) return {};

  const group: Record<string, unknown> = {};
  if (spacing.base_unit) {
    group.base = { $value: spacing.base_unit, $type: "dimension" };
  }
  if (spacing.scale) {
    for (let i = 0; i < spacing.scale.length; i++) {
      group[`scale-${i + 1}`] = {
        $value: `${spacing.scale[i]}px`,
        $type: "dimension",
      };
    }
  }
  return group;
}

function compileSynthesisSpacing(
  synthesis: DesignSynthesisFile,
): Record<string, unknown> {
  const group: Record<string, unknown> = {};

  if (synthesis.spacing.base_unit) {
    group.base = { $value: synthesis.spacing.base_unit, $type: "dimension" };
  }

  synthesis.spacing.component_spacing.forEach((value, index) => {
    group[`component-${index + 1}`] = { $value: value, $type: "dimension" };
  });

  synthesis.spacing.section_spacing.forEach((value, index) => {
    group[`section-${index + 1}`] = { $value: value, $type: "dimension" };
  });

  return group;
}

function compileSignalGroup(
  signals: DesignSynthesisFile["shape"]["radius_scale"] | DesignSynthesisFile["depth"]["shadow_scale"] | DesignSynthesisFile["motion"]["duration_tokens"] | DesignSynthesisFile["motion"]["easing_tokens"],
  type: string,
): Record<string, unknown> {
  const group: Record<string, unknown> = {};

  for (const signal of signals) {
    group[signal.token] = {
      $value: signal.value,
      $type: type,
      $extensions: {
        "com.brandsystem": {
          confidence: signal.confidence,
          provenance: signal.provenance,
        },
      },
    };
  }

  return group;
}

function compileLayout(synthesis: DesignSynthesisFile): Record<string, unknown> {
  const group: Record<string, unknown> = {};

  if (synthesis.layout.content_width) {
    group.contentWidth = {
      $value: synthesis.layout.content_width,
      $type: "dimension",
    };
  }

  group.density = {
    $value: synthesis.layout.density,
    $type: "other",
  };

  group.grid = {
    $value: synthesis.layout.grid_feel,
    $type: "other",
  };

  return group;
}

function compileMotion(synthesis: DesignSynthesisFile): Record<string, unknown> {
  const group: Record<string, unknown> = {};
  const durations = compileSignalGroup(synthesis.motion.duration_tokens, "duration");
  const easings = compileSignalGroup(synthesis.motion.easing_tokens, "cubicBezier");

  if (Object.keys(durations).length > 0) group.duration = durations;
  if (Object.keys(easings).length > 0) group.easing = easings;

  group.tone = {
    $value: synthesis.motion.tone,
    $type: "other",
  };

  return group;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
