import type { CoreIdentityData } from "../schemas/index.js";
import { isTokenWorthy } from "./confidence.js";

/**
 * Compile core-identity.yaml into DTCG tokens.json format.
 * Only includes values with medium+ confidence.
 */
export function compileDTCG(
  identity: CoreIdentityData,
  clientName: string
): Record<string, unknown> {
  const tokens: Record<string, unknown> = {
    $name: `${clientName} Design Tokens`,
    $description: `Generated by brandsystem.app — schema 0.1.0`,
    brand: {
      color: compileColors(identity.colors),
      typography: compileTypography(identity.typography),
    },
  };

  if (identity.spacing) {
    (tokens.brand as Record<string, unknown>).spacing = compileSpacing(identity.spacing);
  }

  return tokens;
}

function compileColors(
  colors: CoreIdentityData["colors"]
): Record<string, unknown> {
  const group: Record<string, unknown> = {};

  for (const color of colors) {
    if (!isTokenWorthy(color.confidence)) continue;

    const key = color.role === "unknown" ? slugify(color.name) : color.role;
    group[key] = {
      $value: color.value,
      $type: "color",
      $description: color.name,
      $extensions: {
        "com.brandsystem": {
          source: color.source,
          confidence: color.confidence,
          ...(color.figma_variable_id && { figmaVariableId: color.figma_variable_id }),
        },
      },
    };
  }

  return group;
}

function compileTypography(
  typography: CoreIdentityData["typography"]
): Record<string, unknown> {
  const group: Record<string, unknown> = {};

  for (const entry of typography) {
    if (!isTokenWorthy(entry.confidence)) continue;

    const key = slugify(entry.name);
    const typeGroup: Record<string, unknown> = {
      family: {
        $value: entry.family,
        $type: "fontFamily",
      },
    };

    if (entry.size) {
      typeGroup.size = { $value: entry.size, $type: "dimension" };
    }
    if (entry.weight) {
      typeGroup.weight = { $value: entry.weight, $type: "fontWeight" };
    }
    if (entry.line_height) {
      typeGroup.lineHeight = { $value: entry.line_height, $type: "dimension" };
    }

    group[key] = typeGroup;
  }

  return group;
}

function compileSpacing(
  spacing: NonNullable<CoreIdentityData["spacing"]>
): Record<string, unknown> {
  if (!isTokenWorthy(spacing.confidence)) return {};

  const group: Record<string, unknown> = {};
  if (spacing.base_unit) {
    group.base = { $value: spacing.base_unit, $type: "dimension" };
  }
  if (spacing.scale) {
    for (let i = 0; i < spacing.scale.length; i++) {
      group[`scale-${i + 1}`] = {
        $value: `${spacing.scale[i]}px`,
        $type: "dimension",
      };
    }
  }
  return group;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
