import type { BrandConfigData, CoreIdentityData, VisualIdentityData } from "../schemas/index.js";

/**
 * Generate a Visual Identity Manifest (VIM) markdown document
 * from compiled brand data (Session 1 core identity + Session 2 visual identity).
 */
export function generateVIM(
  config: BrandConfigData,
  identity: CoreIdentityData,
  visual: VisualIdentityData
): string {
  const lines: string[] = [];

  lines.push(`# ${config.client_name} Visual Identity Manifest v1.0`);
  lines.push("");
  lines.push(`> Generated by brandsystem.app — ${new Date().toISOString().split("T")[0]}`);
  lines.push("");

  // --- 1. Color System ---
  lines.push("## 1. Color System");
  lines.push("");
  lines.push(renderColorPrimitives(identity));
  lines.push(renderSemanticMapping(identity));
  lines.push(renderThemeModes(identity));

  // --- 2. Typography ---
  lines.push("## 2. Typography");
  lines.push("");
  lines.push(renderTypeStack(identity));
  lines.push(renderTypeUsage(identity));

  // --- 3. Composition ---
  lines.push("## 3. Composition");
  lines.push("");
  lines.push(renderSpatialPhilosophy(visual));
  lines.push(renderNegativeSpace(visual));
  lines.push(renderGridLayout(visual));

  // --- 4. Visual Language ---
  lines.push("## 4. Visual Language");
  lines.push("");
  lines.push(renderPatternSystem(visual));
  lines.push(renderIllustrationLanguage(visual));
  lines.push(renderPhotographyDirection(visual));
  lines.push(renderSignatureMoves(visual));

  // --- 5. Logo Usage ---
  lines.push("## 5. Logo Usage");
  lines.push("");
  lines.push(renderLockupRules(identity));
  lines.push(renderAssetReference(identity));

  // --- 6. Compliance Rules ---
  lines.push("## 6. Compliance Rules");
  lines.push("");
  lines.push(renderAntiPatternsHard(visual));
  lines.push(renderAntiPatternsSoft(visual));
  lines.push(renderAutomatedChecks());

  return lines.join("\n");
}

/**
 * Generate a System Integration Guide with real values from the brand data.
 */
export function generateSystemIntegration(
  config: BrandConfigData,
  identity: CoreIdentityData,
  visual: VisualIdentityData
): string {
  const lines: string[] = [];

  lines.push("# System Integration Guide");
  lines.push("");
  lines.push(`> ${config.client_name} — generated by brandsystem.app`);
  lines.push("");

  // --- Quick Setup ---
  lines.push("## Quick Setup (CLAUDE.md / .cursorrules)");
  lines.push("");
  lines.push("Paste the following block into your AI assistant configuration:");
  lines.push("");
  lines.push("```");
  lines.push(renderQuickSetupBlock(config, identity, visual));
  lines.push("```");
  lines.push("");

  // --- Session Start Protocol ---
  lines.push("## Session Start Protocol");
  lines.push("");
  lines.push("1. Run `brand_status` to check the current state of the brand system.");
  lines.push("2. Read `.brand/visual-identity-manifest.md` for the full visual identity spec.");
  lines.push("3. If doing visual work, load `.brand/tokens.json` for exact token values.");
  lines.push("4. If generating copy, check `.brand/core-identity.yaml` for voice and positioning.");
  lines.push("");

  // --- Common Pain Points ---
  lines.push("## Common Pain Points");
  lines.push("");
  lines.push(renderPainPoints(identity, visual));

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Section renderers — Color
// ---------------------------------------------------------------------------

function renderColorPrimitives(identity: CoreIdentityData): string {
  const lines: string[] = [];
  lines.push("### 1a. Primitives");
  lines.push("");

  if (identity.colors.length === 0) {
    lines.push(stub("colors", "brand_extract_web or brand_extract_figma"));
    return lines.join("\n") + "\n";
  }

  lines.push("| Name | Hex | Role | Confidence |");
  lines.push("|------|-----|------|------------|");
  for (const c of identity.colors) {
    lines.push(`| ${c.name} | \`${c.value}\` | ${c.role} | ${c.confidence} |`);
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderSemanticMapping(identity: CoreIdentityData): string {
  const lines: string[] = [];
  lines.push("### 1b. Semantic Mapping");
  lines.push("");

  if (identity.colors.length === 0) {
    lines.push(stub("semantic color mapping", "brand_extract_web or brand_extract_figma"));
    return lines.join("\n") + "\n";
  }

  const byRole = groupBy(identity.colors, (c) => c.role);
  for (const [role, colors] of Object.entries(byRole)) {
    lines.push(`**${capitalize(role)}**`);
    for (const c of colors) {
      lines.push(`- \`${c.value}\` — ${c.name}`);
    }
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

function renderThemeModes(identity: CoreIdentityData): string {
  const lines: string[] = [];
  lines.push("### 1c. Theme Modes");
  lines.push("");

  const hasSurface = identity.colors.some((c) => c.role === "surface");
  const hasText = identity.colors.some((c) => c.role === "text");

  if (!hasSurface && !hasText) {
    lines.push(stub("theme modes", "brand_deepen_identity to define dark/light variants"));
    return lines.join("\n") + "\n";
  }

  lines.push("Theme mapping is derived from surface and text color tokens.");
  lines.push("");
  if (hasSurface) {
    const surfaces = identity.colors.filter((c) => c.role === "surface");
    lines.push("**Surface colors:**");
    for (const s of surfaces) {
      lines.push(`- \`${s.value}\` — ${s.name}`);
    }
    lines.push("");
  }
  if (hasText) {
    const texts = identity.colors.filter((c) => c.role === "text");
    lines.push("**Text colors:**");
    for (const t of texts) {
      lines.push(`- \`${t.value}\` — ${t.name}`);
    }
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Section renderers — Typography
// ---------------------------------------------------------------------------

function renderTypeStack(identity: CoreIdentityData): string {
  const lines: string[] = [];
  lines.push("### 2a. Type Stack");
  lines.push("");

  if (identity.typography.length === 0) {
    lines.push(stub("typography", "brand_extract_web or brand_extract_figma"));
    return lines.join("\n") + "\n";
  }

  lines.push("| Name | Family | Weight | Size | Confidence |");
  lines.push("|------|--------|--------|------|------------|");
  for (const t of identity.typography) {
    lines.push(
      `| ${t.name} | ${t.family} | ${t.weight ?? "—"} | ${t.size ?? "—"} | ${t.confidence} |`
    );
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderTypeUsage(identity: CoreIdentityData): string {
  const lines: string[] = [];
  lines.push("### 2b. Usage");
  lines.push("");

  if (identity.typography.length === 0) {
    lines.push(stub("typography usage", "brand_extract_web or brand_extract_figma"));
    return lines.join("\n") + "\n";
  }

  // Attempt to categorize by name convention
  const headings = identity.typography.filter(
    (t) => /heading|display|title|h[1-6]/i.test(t.name)
  );
  const body = identity.typography.filter(
    (t) => /body|paragraph|text|caption|base/i.test(t.name)
  );
  const mono = identity.typography.filter(
    (t) => /mono|code/i.test(t.name) || /mono/i.test(t.family)
  );
  const other = identity.typography.filter(
    (t) => !headings.includes(t) && !body.includes(t) && !mono.includes(t)
  );

  if (headings.length > 0) {
    lines.push("**Headings:** " + headings.map((t) => `${t.family}`).join(", "));
  }
  if (body.length > 0) {
    lines.push("**Body:** " + body.map((t) => `${t.family}`).join(", "));
  }
  if (mono.length > 0) {
    lines.push("**Monospace:** " + mono.map((t) => `${t.family}`).join(", "));
  }
  if (other.length > 0) {
    lines.push("**Other:** " + other.map((t) => `${t.family} (${t.name})`).join(", "));
  }
  if (headings.length === 0 && body.length === 0 && mono.length === 0 && other.length === 0) {
    lines.push("Run extraction tools to categorize font usage.");
  }

  lines.push("");
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Section renderers — Composition
// ---------------------------------------------------------------------------

function renderSpatialPhilosophy(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 3a. Spatial Philosophy");
  lines.push("");

  if (!visual.composition) {
    lines.push(stub("composition", "brand_deepen_identity"));
    return lines.join("\n") + "\n";
  }

  lines.push(`**Energy:** ${visual.composition.energy}`);
  lines.push(`**Layout preference:** ${visual.composition.layout_preference}`);
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderNegativeSpace(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 3b. Negative Space");
  lines.push("");

  if (!visual.composition) {
    lines.push(stub("negative space rules", "brand_deepen_identity"));
    return lines.join("\n") + "\n";
  }

  lines.push(`**Rule:** ${visual.composition.negative_space}`);
  lines.push("");
  lines.push("This is a measurable constraint. Automated preflight checks negative space ratio.");
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderGridLayout(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 3c. Grid & Layout");
  lines.push("");

  if (!visual.composition) {
    lines.push(stub("grid system", "brand_deepen_identity"));
    return lines.join("\n") + "\n";
  }

  lines.push(`**Grid:** ${visual.composition.grid}`);
  lines.push("");
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Section renderers — Visual Language
// ---------------------------------------------------------------------------

function renderPatternSystem(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 4a. Pattern System");
  lines.push("");

  if (!visual.patterns) {
    lines.push(stub("patterns", "brand_deepen_identity", "patterns questions"));
    return lines.join("\n") + "\n";
  }

  lines.push(`**Type:** ${visual.patterns.type}`);
  lines.push(`**Usage:** ${visual.patterns.usage}`);
  if (visual.patterns.assets.length > 0) {
    lines.push("**Assets:**");
    for (const a of visual.patterns.assets) {
      lines.push(`- \`${a}\``);
    }
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderIllustrationLanguage(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 4b. Illustration Language");
  lines.push("");

  if (!visual.illustration) {
    lines.push(stub("illustration language", "brand_deepen_identity", "illustration questions"));
    return lines.join("\n") + "\n";
  }

  lines.push(`**Style:** ${visual.illustration.style}`);
  lines.push(`**Function:** ${visual.illustration.function}`);
  if (visual.illustration.assets.length > 0) {
    lines.push("**Assets:**");
    for (const a of visual.illustration.assets) {
      lines.push(`- \`${a}\``);
    }
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderPhotographyDirection(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 4c. Photography Direction");
  lines.push("");

  if (!visual.photography) {
    lines.push(stub("photography direction", "brand_deepen_identity", "photography questions"));
    return lines.join("\n") + "\n";
  }

  lines.push(`**Style:** ${visual.photography.style}`);
  if (visual.photography.anti_patterns.length > 0) {
    lines.push("**Avoid:**");
    for (const ap of visual.photography.anti_patterns) {
      lines.push(`- ${ap}`);
    }
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderSignatureMoves(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 4d. Signature Moves");
  lines.push("");

  if (!visual.signature) {
    lines.push(stub("signature moves", "brand_deepen_identity", "signature questions"));
    return lines.join("\n") + "\n";
  }

  lines.push(`**Description:** ${visual.signature.description}`);
  if (visual.signature.elements.length > 0) {
    lines.push("**Elements:**");
    for (const el of visual.signature.elements) {
      lines.push(`- ${el}`);
    }
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Section renderers — Logo
// ---------------------------------------------------------------------------

function renderLockupRules(identity: CoreIdentityData): string {
  const lines: string[] = [];
  lines.push("### 5a. Lockup Rules");
  lines.push("");

  if (identity.logo.length === 0) {
    lines.push(stub("logo lockup rules", "brand_extract_web or brand_extract_figma"));
    return lines.join("\n") + "\n";
  }

  const types = identity.logo.map((l) => l.type);
  const hasWordmark = types.includes("wordmark");
  const hasLogomark = types.includes("logomark");

  if (hasWordmark && hasLogomark) {
    lines.push("Both wordmark and logomark are available.");
    lines.push("**Rule:** Use wordmark OR logomark in a composition — never both together.");
  } else if (hasWordmark) {
    lines.push("Wordmark available. No logomark on file.");
  } else if (hasLogomark) {
    lines.push("Logomark available. No wordmark on file.");
  }
  lines.push("");

  lines.push("Always use the actual SVG/PNG asset files. Never approximate logos with CSS shapes or fonts.");
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderAssetReference(identity: CoreIdentityData): string {
  const lines: string[] = [];
  lines.push("### 5b. Asset Reference");
  lines.push("");

  if (identity.logo.length === 0) {
    lines.push(stub("logo assets", "brand_extract_web or brand_extract_figma"));
    return lines.join("\n") + "\n";
  }

  for (const logo of identity.logo) {
    lines.push(`**${capitalize(logo.type)}** (source: ${logo.source}, confidence: ${logo.confidence})`);
    for (const v of logo.variants) {
      const ref = v.file ? `\`.brand/assets/logo/${v.file}\`` : v.inline_svg ? "inline SVG" : "data URI";
      lines.push(`- ${v.name}: ${ref}`);
    }
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Section renderers — Compliance
// ---------------------------------------------------------------------------

function renderAntiPatternsHard(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 6a. Anti-Patterns (Hard Stops)");
  lines.push("");

  const hardRules = visual.anti_patterns.filter((ap) => ap.severity === "hard");
  if (hardRules.length === 0) {
    lines.push(stub("hard-stop anti-patterns", "brand_deepen_identity", "anti-pattern questions"));
    return lines.join("\n") + "\n";
  }

  for (const rule of hardRules) {
    const pfRef = rule.preflight_id ? ` (preflight: \`${rule.preflight_id}\`)` : "";
    lines.push(`- **${rule.rule}**${pfRef}`);
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderAntiPatternsSoft(visual: VisualIdentityData): string {
  const lines: string[] = [];
  lines.push("### 6b. Soft Guidelines");
  lines.push("");

  const softRules = visual.anti_patterns.filter((ap) => ap.severity === "soft");
  if (softRules.length === 0) {
    lines.push(stub("soft guidelines", "brand_deepen_identity", "anti-pattern questions"));
    return lines.join("\n") + "\n";
  }

  for (const rule of softRules) {
    const pfRef = rule.preflight_id ? ` (preflight: \`${rule.preflight_id}\`)` : "";
    lines.push(`- ${rule.rule}${pfRef}`);
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderAutomatedChecks(): string {
  const lines: string[] = [];
  lines.push("### 6c. Automated Checks");
  lines.push("");
  lines.push("Run `brand_preflight` against any HTML, CSS, or design file to validate compliance.");
  lines.push("The preflight tool checks color usage, typography, logo rules, and anti-patterns automatically.");
  lines.push("");
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// System Integration helpers
// ---------------------------------------------------------------------------

function renderQuickSetupBlock(
  config: BrandConfigData,
  identity: CoreIdentityData,
  visual: VisualIdentityData
): string {
  const lines: string[] = [];

  lines.push(`# ${config.client_name} Brand System`);
  lines.push("");

  // Colors
  if (identity.colors.length > 0) {
    lines.push("## Colors");
    for (const c of identity.colors) {
      lines.push(`- ${capitalize(c.role)}: ${c.value} (${c.name})`);
    }
    lines.push("");
  }

  // Typography
  if (identity.typography.length > 0) {
    lines.push("## Typography");
    const families = [...new Set(identity.typography.map((t) => t.family))];
    for (const fam of families) {
      const entries = identity.typography.filter((t) => t.family === fam);
      const weights = entries
        .filter((e) => e.weight !== undefined)
        .map((e) => e.weight)
        .join(", ");
      lines.push(`- ${fam}${weights ? ` (weights: ${weights})` : ""}`);
    }
    lines.push("");
  }

  // Logo
  if (identity.logo.length > 0) {
    lines.push("## Logo");
    lines.push("ALWAYS use actual SVG/PNG asset files from .brand/assets/logo/.");
    lines.push("NEVER approximate logos with CSS shapes, icon fonts, or text.");
    const types = identity.logo.map((l) => l.type);
    if (types.includes("wordmark") && types.includes("logomark")) {
      lines.push("Use wordmark OR logomark — never both in the same composition.");
    }
    lines.push("");
  }

  // Anti-patterns
  const hardRules = visual.anti_patterns.filter((ap) => ap.severity === "hard");
  if (hardRules.length > 0) {
    lines.push("## Anti-Patterns (NEVER do these)");
    for (const rule of hardRules) {
      lines.push(`- ${rule.rule}`);
    }
    lines.push("");
  }

  const softRules = visual.anti_patterns.filter((ap) => ap.severity === "soft");
  if (softRules.length > 0) {
    lines.push("## Soft Guidelines (avoid unless justified)");
    for (const rule of softRules) {
      lines.push(`- ${rule.rule}`);
    }
    lines.push("");
  }

  // Composition
  if (visual.composition) {
    lines.push("## Composition");
    lines.push(`- Energy: ${visual.composition.energy}`);
    lines.push(`- Negative space: ${visual.composition.negative_space}`);
    lines.push(`- Layout: ${visual.composition.layout_preference}`);
    lines.push(`- Grid: ${visual.composition.grid}`);
    lines.push("");
  }

  // Signature
  if (visual.signature) {
    lines.push("## Signature Moves");
    lines.push(`${visual.signature.description}`);
    for (const el of visual.signature.elements) {
      lines.push(`- ${el}`);
    }
    lines.push("");
  }

  lines.push("## Validation");
  lines.push("Run `brand_preflight` before delivering any visual output.");

  return lines.join("\n");
}

function renderPainPoints(
  identity: CoreIdentityData,
  visual: VisualIdentityData
): string {
  const lines: string[] = [];

  lines.push("### Logo approximation");
  lines.push("");
  if (identity.logo.length > 0) {
    const logoFiles = identity.logo
      .flatMap((l) => l.variants)
      .filter((v) => v.file)
      .map((v) => `.brand/assets/logo/${v.file}`);
    if (logoFiles.length > 0) {
      lines.push(`Your logo files: ${logoFiles.map((f) => `\`${f}\``).join(", ")}`);
      lines.push("");
    }
  }
  lines.push("**Problem:** AI tools often approximate logos with CSS or icon fonts.");
  lines.push("**Fix:** Always read the actual SVG file and use its path data. For web, use the `<symbol>` + `<use>` pattern so `currentColor` inheritance works.");
  lines.push("");

  lines.push("### Wrong colors");
  lines.push("");
  lines.push("**Problem:** AI tools guess colors instead of using exact brand tokens.");
  lines.push("**Fix:** Reference `.brand/tokens.json` for exact values. Use token names, not hex codes, in your code when a token bridge is available.");
  lines.push("");

  lines.push("### Generic output");
  lines.push("");
  lines.push("**Problem:** Output is technically correct but not distinctive — misses the brand's visual personality.");
  if (visual.signature) {
    lines.push(`**Fix:** Apply these signature moves: ${visual.signature.elements.join("; ")}.`);
  } else {
    lines.push("**Fix:** Run `brand_deepen_identity` to define signature moves that make the brand distinctive.");
  }
  if (visual.composition) {
    lines.push(`Remember: composition energy is "${visual.composition.energy}" with ${visual.composition.negative_space} negative space.`);
  }
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function stub(section: string, tool: string, topic?: string): string {
  const topicSuffix = topic ? ` and answer the ${topic}` : "";
  return `**Status: Not yet defined.**\nRun \`${tool}\`${topicSuffix} to populate this section.\n`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function groupBy<T>(arr: T[], keyFn: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of arr) {
    const key = keyFn(item);
    if (!result[key]) result[key] = [];
    result[key].push(item);
  }
  return result;
}
